ekf_filter_node:  # Instead of ekf_node
    ros__parameters:
        use_sim_time: true
        frequency: 30.0
        two_d_mode: false
        publish_acceleration: true
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: /ack_cont/odometry
        odom0_config: [false, false, false,
                      false, false, true,  # Enable yaw orientation
                      true, true, false,
                      false, false, true,
                      false, false, false]


        imu0: imu/data
        imu0_config: [false, false, false,  # Position (not needed)
                      true, true, true,     # Orientation (roll, pitch, yaw)
                      false, false, false,  # Linear velocity
                      true, true, true,     # Angular velocity
                      false, false, false]  # Acceleration