ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true  # Assumes flat ground

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom  # Change to "map" if using localization

    imu0: imu/data
    imu0_config: [false, false, false,  # X, Y, Z position from IMU (unused)
                  true, true, true,    # Roll, pitch, yaw (use orientation)
                  false, false, false,  # Linear velocity
                  true, true, false,    # Angular velocity (yaw only)
                  false, false, false]  # Acceleration (optional)

    odom0: odom
    odom0_config: [true, true, false,  # X, Y position
                   false, false, true,  # Orientation (yaw only)
                   true, true, false,  # Linear velocity
                   false, false, true,  # Angular velocity (yaw only)
                   false, false, false]  # Acceleration (optional)

    process_noise_covariance: [0.05, 0, 0, 0, 0, 0,
                               0, 0.05, 0, 0, 0, 0,
                               0, 0, 0.0001, 0, 0, 0,
                               0, 0, 0, 0.01, 0, 0,
                               0, 0, 0, 0, 0.01, 0,
                               0, 0, 0, 0, 0, 0.01]

    initial_estimate_covariance: [0.1, 0, 0, 0, 0, 0,
                                  0, 0.1, 0, 0, 0, 0,
                                  0, 0, 0.1, 0, 0, 0,
                                  0, 0, 0, 0.1, 0, 0,
                                  0, 0, 0, 0, 0.1, 0,
                                  0, 0, 0, 0, 0, 0.1]
