twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /nav/cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : /joy/cmd_vel
        timeout : 0.5
        priority: 100
      keyboard:
        topic   : /keyboard/cmd_vel
        timeout : 0.5
        priority: 90
      simulatorchair:
        topic   : /simulator_chair/cmd_vel
        timeout : 0.5
        priority: 80