<?xml version="1.0"?>
<robot name="new_car" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="base_length" value="1.65"/>
  <xacro:property name="base_width" value="0.92"/>
  <xacro:property name="base_height" value="1.13"/>

  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="front_wheel_width" value="0.15"/>
  <xacro:property name="rear_wheel_width" value="0.17"/>
  <xacro:property name="front_wheel_ygap" value="0.12"/>
  <xacro:property name="rear_wheel_ygap" value="0.15"/>
  <xacro:property name="wheel_zoff" value="0.123"/>
  <xacro:property name="front_wheel_xoff" value="0.6"/>
  <xacro:property name="rear_wheel_xoff" value="0.45"/>

  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- <box size="${base_length} ${base_width} ${base_height-.2}"/> -->
        <mesh filename="package://robot_description/description/meshes/new_car_chassis.stl" scale="0.58 0.58 0.58"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.0 0.0 1.0 1"/>
      </material>
    </visual>
  </link>

   <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Rear Wheels -->
  <xacro:macro name="rear_wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${rear_wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*rear_wheel_xoff} ${y_reflect*(base_width/2+rear_wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Steering Wheels -->
  <xacro:macro name="steeringwheels" params="prefix x_reflect y_reflect">
    <!-- Steering Link -->
    <link name="${prefix}_steering_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.01" length="0.1"/> <!-- Small cylinder for visual debugging -->
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <!-- Steering Joint -->
    <joint name="${prefix}_steering_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_steering_link"/>
      <origin xyz="${x_reflect*front_wheel_xoff} ${y_reflect*(base_width/2+front_wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="-0.698" upper="0.698" velocity="0.5"/>
    </joint>

    <!-- Wheel Link -->
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${front_wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <!-- Wheel Joint -->
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${prefix}_steering_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

 <xacro:steeringwheels prefix="Front_Left" x_reflect="1" y_reflect="1" />
  <xacro:steeringwheels prefix="Front_Right" x_reflect="1" y_reflect="-1" />
  <xacro:rear_wheel prefix="Rear_Left" x_reflect="-1" y_reflect="1" />
  <xacro:rear_wheel prefix="Rear_Right" x_reflect="-1" y_reflect="-1" />

  <!-- Lidar -->
  <link name="velodyne">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- <box size="${base_length} ${base_width} ${base_height-.2}"/> -->
        <cylinder radius=".0762" length=".0762"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>
  <joint name="velodyne_joint" type="fixed">
    <parent link="base_link"/>
    <child link="velodyne"/>
    <origin xyz ="0 0 1.0414" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo Plugins -->
  <!-- <xacro: include filename = "robot_description/urdf/gazebo_control.xacro" /> -->

</robot>
